services:
  postgresql:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastapi-db
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.14
    ports:
      - "6379:6379"
    volumes:
      - ./.volumes/redis_data:/data  # Redis stores its data in /data directory
    command: redis-server --appendonly yes  # Enable persistence

  rabbitmq:
    image: rabbitmq:3.13.6
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./.volumes/rabbitmq_data:/var/lib/rabbitmq

