"""added fields in users model

Revision ID: c6d732606de0
Revises: 6d6b232fb5ba
Create Date: 2025-02-09 13:25:25.408857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d732606de0'
down_revision = '6d6b232fb5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.Unicode(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.Unicode(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.Unicode(length=255), nullable=True))
    op.add_column('users', sa.Column('check_in_status', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('event_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'events', ['event_id'], ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'event_id')
    op.drop_column('users', 'check_in_status')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
